# Generated by Django 3.1.5 on 2021-01-30 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinic',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='patient',
            name='lon',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='lon',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
