# Generated by Django 2.2.12 on 2021-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='riskFactors',
            field=models.IntegerField(null=True),
        ),
    ]
