# Generated by Django 3.1.5 on 2021-01-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210130_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmationTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='messageSentTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('finished', 'Finished'), ('missed', 'missed')], default='open', max_length=255),
        ),
    ]
