# Generated by Django 2.2.12 on 2021-01-31 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_appointment_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Clinic'),
        ),
    ]
