# Generated by Django 2.2.12 on 2021-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210131_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
