# Generated by Django 2.2.12 on 2021-01-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210131_0151'),
        ('api', '0015_auto_20210131_0844'),
    ]

    operations = [
    ]
